const location = {
  1: {
    stateKr: '서울',
    stateEn: 'Seoul',
    countryAll: [
      { countryNum: 20, countryKr: '강남구', countryEn: 'Gangnam-gu' },
      { countryNum: 21, countryKr: '강동구', countryEn: 'Gangdong-gu' },
      { countryNum: 22, countryKr: '강북구', countryEn: 'Gangbuk-gu' },
      { countryNum: 23, countryKr: '강서구', countryEn: 'Gangseo-gu' },
      { countryNum: 24, countryKr: '관악구', countryEn: 'Gwanak-gu' },
      { countryNum: 25, countryKr: '광진구', countryEn: 'Gwangjin-gu' },
      { countryNum: 26, countryKr: '구로구', countryEn: 'Guro-gu' },
      { countryNum: 27, countryKr: '금천구', countryEn: 'Geumcheon-gu' },
      { countryNum: 28, countryKr: '노원구', countryEn: 'Nowon-gu' },
      { countryNum: 29, countryKr: '도봉구', countryEn: 'Dobong-gu' },
      { countryNum: 30, countryKr: '동대문구', countryEn: 'Dongdaemun-gu' },
      { countryNum: 31, countryKr: '동작구', countryEn: 'Dongjak-gu' },
      { countryNum: 32, countryKr: '마포구', countryEn: 'Mapo-gu' },
      { countryNum: 33, countryKr: '서대문구', countryEn: 'Seodaemun-gu' },
      { countryNum: 34, countryKr: '서초구', countryEn: 'Seocho-gu' },
      { countryNum: 35, countryKr: '성동구', countryEn: 'Seongdong-gu' },
      { countryNum: 36, countryKr: '성북구', countryEn: 'Seongbuk-gu' },
      { countryNum: 37, countryKr: '송파구', countryEn: 'Songpa-gu' },
      { countryNum: 38, countryKr: '양천구', countryEn: 'Yangcheon-gu' },
      { countryNum: 39, countryKr: '영등포구', countryEn: 'Yeongdeungpo-gu' },
      { countryNum: 40, countryKr: '용산구', countryEn: 'Yongsan-gu' },
      { countryNum: 41, countryKr: '은평구', countryEn: 'Eunpyeong-gu' },
      { countryNum: 42, countryKr: '종로구', countryEn: 'Jongno-gu' },
      { countryNum: 43, countryKr: '중구', countryEn: 'Jung-gu' },
      { countryNum: 44, countryKr: '중랑구', countryEn: 'Jungnang-gu' },
    ],
  },
  2: {
    stateKr: '경기',
    stateEn: 'Gyeonggi',
    countryAll: [
      { countryNum: 45, countryKr: '가평군', countryEn: 'Gapyeong-gun' },
      { countryNum: 46, countryKr: '고양시', countryEn: 'Goyang-si' },
      { countryNum: 47, countryKr: '과천시', countryEn: 'Gwacheon-si' },
      { countryNum: 48, countryKr: '광명시', countryEn: 'Gwangmyeong-si' },
      { countryNum: 49, countryKr: '광주시', countryEn: 'Gwangju-si' },
      { countryNum: 50, countryKr: '구리시', countryEn: 'Guri-si' },
      { countryNum: 51, countryKr: '군포시', countryEn: 'Gunpo-si' },
      { countryNum: 52, countryKr: '김포시', countryEn: 'Gimpo-si' },
      { countryNum: 53, countryKr: '남양주시', countryEn: 'Namyangju-si' },
      { countryNum: 54, countryKr: '동두천시', countryEn: 'Dongducheon-si' },
      { countryNum: 55, countryKr: '부천시', countryEn: 'Bucheon-si' },
      { countryNum: 56, countryKr: '성남시', countryEn: 'Seongnam-si' },
      { countryNum: 57, countryKr: '수원시', countryEn: 'Suwon-si' },
      { countryNum: 58, countryKr: '시흥시', countryEn: 'Siheung-si' },
      { countryNum: 59, countryKr: '안산시', countryEn: 'Ansan-si' },
      { countryNum: 60, countryKr: '안성시', countryEn: 'Anseong-si' },
      { countryNum: 61, countryKr: '안양시', countryEn: 'Anyang-si' },
      { countryNum: 62, countryKr: '양주시', countryEn: 'Yangju-si' },
      { countryNum: 63, countryKr: '양평군', countryEn: 'Yangpyeong-gun' },
      { countryNum: 64, countryKr: '여주시', countryEn: 'Yeoju-si' },
      { countryNum: 65, countryKr: '연천군', countryEn: 'Yeoncheon-gun' },
      { countryNum: 66, countryKr: '오산시', countryEn: 'Osan-si' },
      { countryNum: 67, countryKr: '용인시', countryEn: 'Yongin-si' },
      { countryNum: 68, countryKr: '의왕시', countryEn: 'Uiwang-si' },
      { countryNum: 69, countryKr: '의정부시', countryEn: 'Uijeongbu-si' },
      { countryNum: 70, countryKr: '이천시', countryEn: 'Icheon-si' },
      { countryNum: 71, countryKr: '파주시', countryEn: 'Paju-si' },
      { countryNum: 72, countryKr: '평택시', countryEn: 'Pyeongtaek-si' },
      { countryNum: 73, countryKr: '포천시', countryEn: 'Pocheon-si' },
      { countryNum: 74, countryKr: '하남시', countryEn: 'Hanam-si' },
      { countryNum: 75, countryKr: '화성시', countryEn: 'Hwaseong-si' },
    ],
  },
  3: {
    stateKr: '인천',
    stateEn: 'Incheon',
    countryAll: [
      { countryNum: 76, countryKr: '강화군', countryEn: 'Ganghwa-gun' },
      { countryNum: 77, countryKr: '계양구', countryEn: 'Gyeyang-gu' },
      { countryNum: 78, countryKr: '남동구', countryEn: 'Namdong-gu' },
      { countryNum: 79, countryKr: '동구', countryEn: 'Dong-gu' },
      { countryNum: 80, countryKr: '미추홀구', countryEn: 'Michuhol-gu' },
      { countryNum: 81, countryKr: '부평구', countryEn: 'Bupyeong-gu' },
      { countryNum: 82, countryKr: '서구', countryEn: 'Seo-gu' },
      { countryNum: 83, countryKr: '연수구', countryEn: 'Yeonsu-gu' },
      { countryNum: 84, countryKr: '옹진군', countryEn: 'Ongjin-gun' },
      { countryNum: 85, countryKr: '중구', countryEn: 'Jung-gu' },
    ],
  },
  4: {
    stateKr: '강원',
    stateEn: 'Gangwon',
    countryAll: [
      { countryNum: 86, countryKr: '강릉시', countryEn: 'Gangneung-si' },
      { countryNum: 87, countryKr: '고성군', countryEn: 'Goseong-gun' },
      { countryNum: 88, countryKr: '동해시', countryEn: 'Donghae-si' },
      { countryNum: 89, countryKr: '삼척시', countryEn: 'Samcheok-si' },
      { countryNum: 90, countryKr: '속초시', countryEn: 'Sokcho-si' },
      { countryNum: 91, countryKr: '양구군', countryEn: 'Yanggu-gun' },
      { countryNum: 92, countryKr: '양양군', countryEn: 'Yangyang-gun' },
      { countryNum: 93, countryKr: '영월군', countryEn: 'Yeongwol-gun' },
      { countryNum: 94, countryKr: '원주시', countryEn: 'Wonju-si' },
      { countryNum: 95, countryKr: '인제군', countryEn: 'Inje-gun' },
      { countryNum: 96, countryKr: '정선군', countryEn: 'Jeongseon-gun' },
      { countryNum: 97, countryKr: '철원군', countryEn: 'Cheorwon-gun' },
      { countryNum: 98, countryKr: '춘천시', countryEn: 'Chuncheon-si' },
      { countryNum: 99, countryKr: '태백시', countryEn: 'Taebaek-si' },
      { countryNum: 100, countryKr: '평창군', countryEn: 'Pyeongchang-gun' },
      { countryNum: 101, countryKr: '홍천군', countryEn: 'Hongcheon-gun' },
      { countryNum: 102, countryKr: '화천군', countryEn: 'Hwacheon-gun' },
      { countryNum: 103, countryKr: '횡성군', countryEn: 'Hoengseong-gun' },
    ],
  },
  5: {
    stateKr: '충남',
    stateEn: 'Chungnam',
    countryAll: [
      { countryNum: 104, countryKr: '계룡시', countryEn: 'Gyeryong-si' },
      { countryNum: 105, countryKr: '공주시', countryEn: 'Gongju-si' },
      { countryNum: 106, countryKr: '금산군', countryEn: 'Geumsan-gun' },
      { countryNum: 107, countryKr: '논산시', countryEn: 'Nonsan-si' },
      { countryNum: 108, countryKr: '당진시', countryEn: 'Dangjin-si' },
      { countryNum: 109, countryKr: '보령시', countryEn: 'Boryeong-si' },
      { countryNum: 110, countryKr: '부여군', countryEn: 'Buyeo-gun' },
      { countryNum: 111, countryKr: '서산시', countryEn: 'Seosan-si' },
      { countryNum: 112, countryKr: '서천군', countryEn: 'Seocheon-gun' },
      { countryNum: 113, countryKr: '아산시', countryEn: 'Asan-si' },
      { countryNum: 114, countryKr: '예산군', countryEn: 'Yesan-gun' },
      { countryNum: 115, countryKr: '천안시', countryEn: 'Cheonan-si' },
      { countryNum: 116, countryKr: '청양군', countryEn: 'Cheongyang-gun' },
      { countryNum: 117, countryKr: '태안군', countryEn: 'Taean-gun' },
      { countryNum: 118, countryKr: '홍성군', countryEn: 'Hongseong-gun' },
    ],
  },
  6: {
    stateKr: '충북',
    stateEn: 'Chungbuk',
    countryAll: [
      { countryNum: 119, countryKr: '괴산군', countryEn: 'Goesan-gun' },
      { countryNum: 120, countryKr: '단양군', countryEn: 'Danyang-gun' },
      { countryNum: 121, countryKr: '보은군', countryEn: 'Boeun-gun' },
      { countryNum: 122, countryKr: '영동군', countryEn: 'Yeongdong-gun' },
      { countryNum: 123, countryKr: '옥천군', countryEn: 'Okcheon-gun' },
      { countryNum: 124, countryKr: '음성군', countryEn: 'Eumseong-gun' },
      { countryNum: 125, countryKr: '제천시', countryEn: 'Jecheon-si' },
      { countryNum: 126, countryKr: '증평군', countryEn: 'Jeungpyeong-gun' },
      { countryNum: 127, countryKr: '진천군', countryEn: 'Jincheon-gun' },
      { countryNum: 128, countryKr: '청주시', countryEn: 'Cheongju-si' },
      { countryNum: 129, countryKr: '충주시', countryEn: 'Chungju-si' },
    ],
  },
  7: {
    stateKr: '대전',
    stateEn: 'Daejeon',
    countryAll: [
      { countryNum: 130, countryKr: '대덕구', countryEn: 'Daedeok-gu' },
      { countryNum: 131, countryKr: '동구', countryEn: 'Dong-gu' },
      { countryNum: 132, countryKr: '서구', countryEn: 'Seo-gu' },
      { countryNum: 133, countryKr: '유성구', countryEn: 'Yuseong-gu' },
      { countryNum: 134, countryKr: '중구', countryEn: 'Jung-gu' },
    ],
  },
  8: {
    stateKr: '세종',
    stateEn: 'Sejong',
    countryAll: [
      { countryNum: 135, countryKr: '세종시', countryEn: 'Sejong-si' },
    ],
  },
  9: {
    stateKr: '경남',
    stateEn: 'Gyeongnam',
    countryAll: [
      { countryNum: 136, countryKr: '거제시', countryEn: 'Geoje-si' },
      { countryNum: 137, countryKr: '거창군', countryEn: 'Geochang-gun' },
      { countryNum: 138, countryKr: '고성군', countryEn: 'Goseong-gun' },
      { countryNum: 139, countryKr: '김해시', countryEn: 'Gimhae-si' },
      { countryNum: 140, countryKr: '남해군', countryEn: 'Namhae-gun' },
      { countryNum: 141, countryKr: '밀양시', countryEn: 'Miryang-si' },
      { countryNum: 142, countryKr: '사천시', countryEn: 'Sacheon-si' },
      { countryNum: 143, countryKr: '산청군', countryEn: 'Sancheong-gun' },
      { countryNum: 144, countryKr: '양산시', countryEn: 'Yangsan-si' },
      { countryNum: 145, countryKr: '의령군', countryEn: 'Uiryeong-gun' },
      { countryNum: 146, countryKr: '진주시', countryEn: 'Jinju-si' },
      { countryNum: 147, countryKr: '창녕군', countryEn: 'Changnyeong-gun' },
      { countryNum: 148, countryKr: '창원시', countryEn: 'Changwon-si' },
      { countryNum: 149, countryKr: '통영시', countryEn: 'Tongyeong-si' },
      { countryNum: 150, countryKr: '하동군', countryEn: 'Hadong-gun' },
      { countryNum: 151, countryKr: '함안군', countryEn: 'Haman-gun' },
      { countryNum: 152, countryKr: '함양군', countryEn: 'Hamyang-gun' },
      { countryNum: 153, countryKr: '합천군', countryEn: 'Hapcheon-gun' },
    ],
  },
  10: {
    stateNum: 10,
    stateKr: '경북',
    stateEn: 'Gyeongbuk',
    countryAll: [
      { countryNum: 154, countryKr: '경산시', countryEn: 'Gyeongsan-si' },
      { countryNum: 155, countryKr: '경주시', countryEn: 'Gyeongju-si' },
      { countryNum: 156, countryKr: '고령군', countryEn: 'Goryeong-Gun' },
      { countryNum: 157, countryKr: '구미시', countryEn: 'Gumi-si' },
      { countryNum: 158, countryKr: '군위군', countryEn: 'Gunwi-gun' },
      { countryNum: 159, countryKr: '김천시', countryEn: 'Gimcheon-si' },
      { countryNum: 160, countryKr: '문경시', countryEn: 'Mungyeong-si' },
      { countryNum: 161, countryKr: '봉화군', countryEn: 'Bonghwa-gun' },
      { countryNum: 162, countryKr: '상주시', countryEn: 'Sangju-si' },
      { countryNum: 163, countryKr: '성주군', countryEn: 'Seongju-gun' },
      { countryNum: 164, countryKr: '안동시', countryEn: 'Andong-si' },
      { countryNum: 165, countryKr: '영덕군', countryEn: 'Yeongdeok-gun' },
      { countryNum: 166, countryKr: '영양군', countryEn: 'Yeongyang-gun' },
      { countryNum: 167, countryKr: '영주시', countryEn: 'Yeongju-si' },
      { countryNum: 168, countryKr: '영천시', countryEn: 'Yeongcheon-si' },
      { countryNum: 169, countryKr: '예천군', countryEn: 'Yecheon-gun' },
      { countryNum: 170, countryKr: '울릉군', countryEn: 'Ulleung-gun' },
      { countryNum: 171, countryKr: '울진군', countryEn: 'Uljin-gun' },
      { countryNum: 172, countryKr: '의성군', countryEn: 'Uiseong-gun' },
      { countryNum: 173, countryKr: '청도군', countryEn: 'Cheongdo-gun' },
      { countryNum: 174, countryKr: '청송군', countryEn: 'Cheongsong-gun' },
      { countryNum: 175, countryKr: '칠곡군', countryEn: 'Chilgok-gun' },
      { countryNum: 176, countryKr: '포항시', countryEn: 'Pohang-si' },
    ],
  },
  11: {
    stateKr: '부산',
    stateEn: 'Busan',
    countryAll: [
      { countryNum: 177, countryKr: '강서구', countryEn: 'Gangseo-gu' },
      { countryNum: 178, countryKr: '금정구', countryEn: 'Geumjeong-gu' },
      { countryNum: 179, countryKr: '기장군', countryEn: 'Gijang-gun' },
      { countryNum: 180, countryKr: '남구', countryEn: 'Nam-gu' },
      { countryNum: 181, countryKr: '동구', countryEn: 'Dong-gu' },
      { countryNum: 182, countryKr: '동래구', countryEn: 'Dongnae-gu' },
      { countryNum: 183, countryKr: '부산진구', countryEn: 'Busanjin-gu' },
      { countryNum: 184, countryKr: '북구', countryEn: 'Buk-gu' },
      { countryNum: 185, countryKr: '사상구', countryEn: 'Sasang-gu' },
      { countryNum: 186, countryKr: '사하구', countryEn: 'Saha-gu' },
      { countryNum: 187, countryKr: '서구', countryEn: 'Seo-gu' },
      { countryNum: 188, countryKr: '수영구', countryEn: 'Suyeong-gu' },
      { countryNum: 189, countryKr: '연제구', countryEn: 'Yeonje-gu' },
      { countryNum: 190, countryKr: '영도구', countryEn: 'Yeongdo-gu' },
      { countryNum: 191, countryKr: '중구', countryEn: 'Jung-gu' },
      { countryNum: 192, countryKr: '해운대구', countryEn: 'Haeundae-gu' },
    ],
  },
  12: {
    stateKr: '대구',
    stateEn: 'Daegu',
    countryAll: [
      { countryNum: 193, countryKr: '남구', countryEn: 'Nam-gu' },
      { countryNum: 194, countryKr: '달서구', countryEn: 'Dalseo-gu' },
      { countryNum: 195, countryKr: '달성군', countryEn: 'Dalseong-gun' },
      { countryNum: 196, countryKr: '동구', countryEn: 'Dong-gu' },
      { countryNum: 197, countryKr: '북구', countryEn: 'Buk-gu' },
      { countryNum: 198, countryKr: '서구', countryEn: 'Seo-gu' },
      { countryNum: 199, countryKr: '수성구', countryEn: 'Suseong-gu' },
      { countryNum: 200, countryKr: '중구', countryEn: 'Jung-gu' },
    ],
  },
  13: {
    stateKr: '울산',
    stateEn: 'Ulsan',
    countryAll: [
      { countryNum: 201, countryKr: '남구', countryEn: 'Nam-gu' },
      { countryNum: 202, countryKr: '동구', countryEn: 'Dong-gu' },
      { countryNum: 203, countryKr: '북구', countryEn: 'Buk-gu' },
      { countryNum: 204, countryKr: '울주군', countryEn: 'Ulju-gun' },
      { countryNum: 205, countryKr: '중구', countryEn: 'Jung-gu' },
    ],
  },
  14: {
    stateKr: '전남',
    stateEn: 'Jeonnam',
    countryAll: [
      { countryNum: 206, countryKr: '강진군', countryEn: 'Gangjin-gun' },
      { countryNum: 207, countryKr: '고흥군', countryEn: 'Goheung-gun' },
      { countryNum: 208, countryKr: '곡성군', countryEn: 'Gokseong-gun' },
      { countryNum: 209, countryKr: '광양시', countryEn: 'Gwangyang-si' },
      { countryNum: 210, countryKr: '구례군', countryEn: 'Gurye-gun' },
      { countryNum: 211, countryKr: '나주시', countryEn: 'Naju-si' },
      { countryNum: 212, countryKr: '담양군', countryEn: 'Damyang-gun' },
      { countryNum: 213, countryKr: '목포시', countryEn: 'Mokpo-si' },
      { countryNum: 214, countryKr: '무안군', countryEn: 'Muan-gun' },
      { countryNum: 215, countryKr: '보성군', countryEn: 'Boseong-gun' },
      { countryNum: 216, countryKr: '순천시', countryEn: 'Suncheon-si' },
      { countryNum: 217, countryKr: '신안군', countryEn: 'Sinan-gun' },
      { countryNum: 218, countryKr: '여수시', countryEn: 'Yeosu-si' },
      { countryNum: 219, countryKr: '영광군', countryEn: 'Yeonggwang-gun' },
      { countryNum: 220, countryKr: '영암군', countryEn: 'Yeongam-gun' },
      { countryNum: 221, countryKr: '완도군', countryEn: 'Wando-gun' },
      { countryNum: 222, countryKr: '장성군', countryEn: 'Jangseong-gun' },
      { countryNum: 223, countryKr: '장흥군', countryEn: 'Jangheung-gun' },
      { countryNum: 224, countryKr: '진도군', countryEn: 'Jindo-gun' },
      { countryNum: 225, countryKr: '함평군', countryEn: 'Hampyeong-gun' },
      { countryNum: 226, countryKr: '해남군', countryEn: 'Haenam-gun' },
      { countryNum: 227, countryKr: '화순군', countryEn: 'Hwasun-gun' },
    ],
  },
  15: {
    stateKr: '전북',
    stateEn: 'Jeonbuk',
    countryAll: [
      { countryNum: 228, countryKr: '고창군', countryEn: 'Gochang-gun' },
      { countryNum: 229, countryKr: '군산시', countryEn: 'Gunsan-si' },
      { countryNum: 230, countryKr: '김제시', countryEn: 'Gimje-si' },
      { countryNum: 231, countryKr: '남원시', countryEn: 'Namwon-si' },
      { countryNum: 232, countryKr: '덕진구', countryEn: 'Deokjin-gu' },
      { countryNum: 233, countryKr: '무주군', countryEn: 'Muju-gun' },
      { countryNum: 234, countryKr: '부안군', countryEn: 'Buan-gun' },
      { countryNum: 235, countryKr: '순창군', countryEn: 'Sunchang-gun' },
      { countryNum: 236, countryKr: '완산구', countryEn: 'Wansan-gu' },
      { countryNum: 237, countryKr: '완주군', countryEn: 'Wanju-gun' },
      { countryNum: 238, countryKr: '익산시', countryEn: 'Iksan-si' },
      { countryNum: 239, countryKr: '임실군', countryEn: 'Imsil-gun' },
      { countryNum: 240, countryKr: '장수군', countryEn: 'Jangsu-gun' },
      { countryNum: 241, countryKr: '전주시', countryEn: 'Jeonju-si' },
      { countryNum: 242, countryKr: '정읍시', countryEn: 'Jeongeup-si' },
      { countryNum: 243, countryKr: '진안군', countryEn: 'Jinan-gun' },
    ],
  },
  16: {
    stateKr: '광주',
    stateEn: 'Gwangju',
    countryAll: [
      { countryNum: 244, countryKr: '광산구', countryEn: 'Gwangsan-gu' },
      { countryNum: 245, countryKr: '남구', countryEn: 'Nam-gu' },
      { countryNum: 246, countryKr: '동구', countryEn: 'Dong-gu' },
      { countryNum: 247, countryKr: '북구', countryEn: 'Buk-gu' },
      { countryNum: 248, countryKr: '서구', countryEn: 'Seo-gu' },
    ],
  },
  17: {
    stateKr: '제주',
    stateEn: 'Jeju',
    countryAll: [
      { countryNum: 249, countryKr: '서귀포시', countryEn: 'Seogwipo-si' },
      { countryNum: 250, countryKr: '제주시', countryEn: 'Jeju-si' },
    ],
  },
}
