const express = require('express')
const router = express.Router()
const Store = require('../../models/StoreModel')

const list = [
  {
    dataNumber: 1,
    listing: true,
    state: '6',
    country: '162',
    sectors: '일식',
    logo: '%EB%B4%89%EB%93%9D%EC%8B%9D%EB%8B%B9.png',
    name: '봉득식당',
    address: '충북 청주시 청원구 수암로88번길 15',
    openTime: '11:00~23:00',
    breakTime: '14:30~15:30',
    lastOrderTime: '없음',
    closed: '토요일',
    contact: '043-222-2371',
    channelName: 1,
    thumbnail: '1.jpg',
    link: 'https://youtu.be/WmtX6Bd8p-w',
    title: '폐업하고 막노동하러 가기 일보직전인 사장님 (유튜브판 골목식당)',
    onAir: '2020-10-31',
  },
  {
    dataNumber: 2,
    listing: true,
    state: '1',
    country: '44',
    sectors: '고기/구이',
    logo: '%EC%9C%A1%EB%8C%80%ED%8F%AC+%EB%A1%9C%EA%B3%A0.png',
    name: '육대포',
    address: '서울 중랑구 중랑천로12길 79 1층 육대포',
    openTime: '17:00~24:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '월요일',
    contact: '010-3072-7447',
    channelName: 1,
    thumbnail: '2.jpg',
    link: 'https://youtu.be/KXnInk46uJw',
    title: '배달알바해서 직원월급 주는 사장님 (유튜브판 골목식당)',
    onAir: '2021-06-05',
  },
  {
    dataNumber: 3,
    listing: true,
    state: '1',
    country: '30',
    sectors: '한식',
    logo: '%EC%82%BC%EB%B3%B5%ED%95%9C%EB%B0%A9%EB%8B%AD%ED%95%9C%EB%A7%88%EB%A6%AC+%EB%A1%9C%EA%B3%A0.png',
    name: '삼복한방닭한마리',
    address: '서울 동대문구 회기로16길 5-1 1층 삼복한방닭한마리',
    openTime: '11:00~22:00',
    breakTime: '없음',
    lastOrderTime: '전화 후 방문',
    closed: '월요일',
    contact: '02-966-4843',
    channelName: 1,
    thumbnail: '3.jpg',
    link: 'https://youtu.be/KgxhVF2eRjk',
    title: '두 번 망하고 세 번째 창업했지만 월매출 600 (유튜브판 골목식당)',
    onAir: '2021-06-10',
  },
  {
    dataNumber: 4,
    listing: true,
    state: '2',
    country: '59',
    sectors: '고기/구이',
    logo: '%EB%9E%AD%EC%82%BC%EC%A7%91+%EB%A1%9C%EA%B3%A0.png',
    name: '랭삼집',
    address: '경기 안산시 상록구 광덕산안길 14 103호',
    openTime: '17:00~24:00',
    breakTime: '없음',
    lastOrderTime: '23:30',
    closed: '없음',
    contact: '031-403-2728',
    channelName: 1,
    thumbnail: '4.jpg',
    link: 'https://youtu.be/Mub7YOIOImk',
    title: '한달 100만원도 못벌어가는 냉삼겹 사장님 (유튜브판 골목식당)',
    onAir: '2021-06-20',
  },
  {
    dataNumber: 5,
    listing: true,
    state: '2',
    country: '59',
    sectors: '치킨/피자',
    logo: '%EA%B0%80%EC%84%B1%EB%B9%84%EC%B5%9C%EA%B3%A0%EC%9D%98%EC%B9%98%ED%82%A8%EC%A7%91+%EB%A1%9C%EA%B3%A0.png',
    name: '가성비최고의치킨집',
    address: '경기 안산시 상록구 광덕산안길 14',
    openTime: '16:00~02:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '031-410-2728',
    channelName: 1,
    thumbnail: '5.jpg',
    link: 'https://youtu.be/DfwaPb8HaeI',
    title: '한 달 200도 못벌어가는 치킨집 사장님(유튜브판 골목식당)',
    onAir: '2021-06-25',
  },
  {
    dataNumber: 6,
    listing: true,
    state: '1',
    country: '42',
    sectors: '버거/양식',
    logo: '%EB%B2%85%EB%B2%85%EB%B2%84%EA%B1%B0+%EB%A1%9C%EA%B3%A0.png',
    name: '벅벅버거',
    address: '서울 종로구 명륜길 48 벅벅',
    openTime: '(월~토) 11:00~01:00\n(일) 13:00~22:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '일요일 13:00~22:00',
    contact: '010-5739-9909',
    channelName: 1,
    thumbnail: '6.jpg',
    link: 'https://youtu.be/CM3iE2XJQZ4',
    title:
      '매달200씩 적자! 못버티고 직원까지 내보내게 된 사장님 (유튜브판 골목식당)',
    onAir: '2021-06-30',
  },
  {
    dataNumber: 7,
    listing: true,
    state: '2',
    country: '59',
    sectors: '고기/구이',
    logo: '%EB%8F%99%ED%95%B4%EA%B0%88%EB%A7%A4%EA%B8%B0+%EB%A1%9C%EA%B3%A0.png',
    name: '동해갈매기',
    address: '경기 안산시 상록구 각골로 60 2층 동해갈매기',
    openTime: '(월~토) 12:00~23:00\n(일) 12:00~22:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '일요일 12:00~22:00',
    contact: '031-507-9292',
    channelName: 1,
    thumbnail: '7.jpg',
    link: 'https://youtu.be/HEFs2B1wvvI',
    title: '오픈 두 달 됐는데 매달 300씩 까먹는 사장님 (유튜브판 골목식당)',
    onAir: '2021-07-05',
  },
  {
    dataNumber: 8,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '삼복한방닭한마리',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '8.jpg',
    link: 'https://youtu.be/9p7tbKIUv1I',
    title: '두 번 망하고 또 망하기 일보직전이었던 닭한마리맛집 ',
    onAir: '2021-07-10',
  },
  {
    dataNumber: 9,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '벅벅버거',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '9.jpg',
    link: 'https://youtu.be/UosUIvMG3FE',
    title: '매달200씩 적자에 알바 권고사직 권유했던 벅벅 ',
    onAir: '2021-07-15',
  },
  {
    dataNumber: 10,
    listing: true,
    state: '1',
    country: '35',
    sectors: '치킨/피자',
    logo: '%EC%83%90%ED%94%BC+%EB%A1%9C%EA%B3%A0.png',
    name: '샐피',
    address: '서울 성동구 마조로5길 3 지하1층',
    openTime: '10:00~22:00',
    breakTime: '15:30~16:30',
    lastOrderTime: '14:45,21:15',
    closed: '없음',
    contact: '02-2292-9902',
    channelName: 1,
    thumbnail: '10.jpg',
    link: 'https://youtu.be/DIacFBPvHj4',
    title: '망하기일보직전 신라호텔출신 사장님 (유튜브판 골목식당)',
    onAir: '2021-07-20',
  },
  {
    dataNumber: 11,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '샐피',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '11.jpg',
    link: 'https://youtu.be/frmGdXtMKHk',
    title: '망하기일보직전 신라호텔출신 사장님,샐피 ',
    onAir: '2021-07-27',
  },
  {
    dataNumber: 12,
    listing: true,
    state: '1',
    country: '41',
    sectors: '분식',
    logo: "%EB%B0%A5's%ED%8B%B1+%EB%A1%9C%EA%B3%A0.png",
    name: '밥s틱',
    address: '서울 은평구 갈현로33길 13 1층 밥’s틱',
    openTime: '11:00~22:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '둘째주,넷째주 월요일',
    contact: '02-356-6934',
    channelName: 1,
    thumbnail: '12.jpg',
    link: 'https://youtu.be/lccPDo6MzRw',
    title:
      '노가다해서 모은 돈 3천으로 창업했지만 망하기 일보직전 (유튜브판 골목식당)',
    onAir: '2021-08-01',
  },
  {
    dataNumber: 13,
    listing: true,
    state: '2',
    country: '57',
    sectors: '고기/구이',
    logo: '%EB%8F%BC%ED%86%B5%EB%A0%B9+%EB%A1%9C%EA%B3%A0.png',
    name: '돼통령',
    address: '경기 수원시 팔달구 권광로188번길 41 1층 돼통령',
    openTime: '12:00~24:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '031-890-6668',
    channelName: 1,
    thumbnail: '13.jpg',
    link: 'https://youtu.be/mV5G3VKBJW4',
    title: '월세440짜리에 고기집 차린 27살 ',
    onAir: '2021-08-04',
  },
  {
    dataNumber: 14,
    listing: true,
    state: '1',
    country: '40',
    sectors: '보쌈/족발',
    logo: '%EB%A7%8C%EB%A6%AC%EC%82%BC%EA%B5%AC%EB%B3%B4%EC%8C%88%EC%A1%B1%EB%B0%9C+%EB%A1%9C%EA%B3%A0.png',
    name: '만리삼구보쌈족발',
    address: '서울 용산구 효창원로 270 만리삼구보쌈',
    openTime: '11:00~22:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '수요일',
    contact: '02-711-3953',
    channelName: 1,
    thumbnail: '14.jpg',
    link: 'https://youtu.be/OH0FJ5Iw_UE',
    title: '하루 2개 파는 족발집 맛 없다고하면 폐업한다고 합니다 ',
    onAir: '2021-08-13',
  },
  {
    dataNumber: 15,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '밥s틱',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '15.jpg',
    link: 'https://youtu.be/34JM4ahe7ls',
    title: '하루10개도 못 팔던 밥스틱, 솔루션 후 200개씩 팔리는중! ',
    onAir: '2021-08-18',
  },
  {
    dataNumber: 16,
    listing: true,
    state: '1',
    country: '20',
    sectors: '카페/디저트',
    logo: '%EC%82%BC%EC%82%BC%EA%B3%B5%EB%8D%B0%EC%9D%B4+%EB%A1%9C%EA%B3%A0.png',
    name: '삼삼공데이',
    address: '서울 강남구 논현로 507 성지하이츠3차 B1층 6호',
    openTime: '08:00~04:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '토요일,일요일',
    contact: '010-5363-1528',
    channelName: 1,
    thumbnail: '16.jpg',
    link: 'https://youtu.be/WWOAqZdRESI',
    title: '장사가안돼서 길바닥에서 전단지 돌리는 여사장님 ',
    onAir: '2021-08-23',
  },
  {
    dataNumber: 17,
    listing: true,
    state: '2',
    country: '66',
    sectors: '족발/보쌈',
    logo: '%EB%B0%95%EA%B4%91%EB%8D%95+%EC%B2%9C%ED%95%98%EC%9E%A5%EC%82%AC+%EC%A1%B1%EB%B0%9C+%EB%A1%9C%EA%B3%A0.png',
    name: '박광덕 천하장사 족발',
    address: '경기 오산시 대원로 32',
    openTime: '13:00~22:00',
    breakTime: '없음',
    lastOrderTime: '전화 후 방문',
    closed: '일요일',
    contact: '0507-1479-8287',
    channelName: 1,
    thumbnail: '17.jpg',
    link: 'https://youtu.be/pUguEUHwI-g',
    title:
      '박광덕 족발 먹방 찍으러갔다가 솔루션 하고왔습니다 (유튜브판 골목식당)',
    onAir: '2021-08-28',
  },
  {
    dataNumber: 18,
    listing: true,
    state: '1',
    country: '27',
    sectors: '버거/양식',
    logo: '%EC%9B%B0%EB%8D%98+%EB%A1%9C%EA%B3%A0.png',
    name: '웰던',
    address: '서울 금천구 남부순환로128길 15 1층 웰던',
    openTime: '11:30~24:00',
    breakTime: '없음',
    lastOrderTime: '23:30',
    closed: '없음',
    contact: '070-4036-5236',
    channelName: 1,
    thumbnail: '18.jpg',
    link: 'https://youtu.be/D71fzvp-NPk',
    title:
      '손님이 너무없어 44만원 모으려면 한달 걸린다는 사장님 (유튜브판 골목식당)',
    onAir: '2021-09-02',
  },
  {
    dataNumber: 19,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '돼통령',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '19.jpg',
    link: 'https://youtu.be/1zd7djMuoog',
    title: '월세가 너무 비싸 배달대행으로 월세 메꾸던 27살 ',
    onAir: '2021-09-07',
  },
  {
    dataNumber: 20,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '만리삼구보쌈족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '20.jpg',
    link: 'https://youtu.be/51QyKg4barY',
    title: '맛 없으면 폐업한다던 만리삼구보쌈족발 ',
    onAir: '2021-09-17',
  },
  {
    dataNumber: 21,
    listing: true,
    state: '1',
    country: '26',
    sectors: '치킨/피자',
    logo: '%EC%B9%98%EC%A6%88%EC%8A%A4%EB%A7%88%EC%9D%BC+%EB%A1%9C%EA%B3%A0.png',
    name: '치즈스마일',
    address: '서울 구로구 개봉로3가길 59 1층',
    openTime: '10:00~00:30',
    breakTime: '없음',
    lastOrderTime: '전화 후 주문',
    closed: '없음',
    contact: '02-2060-8972',
    channelName: 1,
    thumbnail: '21.jpg',
    link: 'https://youtu.be/ZslceDXePhU',
    title: '하루 18시간씩 일하고 한달 200도 못버는 사장님 (유튜브판 골목식당)',
    onAir: '2021-09-22',
  },
  {
    dataNumber: 22,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '랭삼집',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '22.jpg',
    link: 'https://youtu.be/Ld7e3TBdglc',
    title: '파리만 날리던 랭삼겹, 솔루션 후 매일 꽉 참 (유튜브판 골목식당)',
    onAir: '2021-10-02',
  },
  {
    dataNumber: 23,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '박광덕 천하장사 족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '23.jpg',
    link: 'https://youtu.be/o8otFwFkvCY',
    title: '박광덕족발 중간점검',
    onAir: '2021-10-08',
  },
  {
    dataNumber: 24,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '치즈스마일',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '24.jpg',
    link: 'https://youtu.be/3lArDQGHS8I',
    title: '가게에서 먹고 자던 피자집 여사장님 ',
    onAir: '2021-10-18',
  },
  {
    dataNumber: 25,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '치즈스마일',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '25.jpg',
    link: 'https://youtu.be/yWr--ea8_w0',
    title: '핵미모 여사장님의 충격적인 반전(feat.대하먹방)',
    onAir: '2021-10-23',
  },
  {
    dataNumber: 26,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '육대포',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '26.jpg',
    link: 'https://youtu.be/-O2K4girEBc',
    title: '국내산 싸대기 때릴만큼 맛있는 5,500원 흑돼지 꽃목살(육대포 먹방)',
    onAir: '2021-10-30',
  },
  {
    dataNumber: 27,
    listing: true,
    state: '1',
    country: '38',
    sectors: '일식',
    logo: '%ED%98%B8%EB%8F%88%EB%8F%88%EA%B0%80%EC%8A%A4+%EB%A1%9C%EA%B3%A0.png',
    name: '호돈돈가스',
    address: '서울 양천구 신월로 132',
    openTime: '11:00~21:00',
    breakTime: '15:30~17:00',
    lastOrderTime: '전화 후 방문',
    closed: '없음',
    contact: '0507-1399-7789',
    channelName: 1,
    thumbnail: '27.jpg',
    link: 'https://youtu.be/zIkTBjIM2zU',
    title:
      '연돈보다 맛있는 호돈, 망해가는 이유는 손님을 쌩깜(유튜브판 골목식당)',
    onAir: '2021-11-06',
  },
  {
    dataNumber: 28,
    listing: true,
    state: '3',
    country: '83',
    sectors: '한식',
    logo: '%EC%A7%84%ED%95%9C%EC%8B%9D%EB%8B%B9+%EB%A1%9C%EA%B3%A0.png',
    name: '진한식당',
    address:
      '인천 연수구 인천타워대로 323 송도 센트로드 상가동(D동) 211, 212호',
    openTime: '04:30~14:00',
    breakTime: '08:00~10:30',
    lastOrderTime: '없음',
    closed: '일요일',
    contact: '0507-1374-1556',
    channelName: 1,
    thumbnail: '28.jpg',
    link: 'https://youtu.be/JneKOUoGBuY',
    title:
      '1인당6000원 한식뷔페로 연매출15억찍는 찐핵미모 여사장님 (유튜브판 골목식당)',
    onAir: '2021-11-14',
  },
  {
    dataNumber: 29,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '호돈돈가스',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '29.jpg',
    link: 'https://youtu.be/A_iP-olAW6s',
    title:
      '연돈이 되고 싶은 돈가스 사장님,밥도 못먹고 이틀째못잠,중간점검(유튜브판 골목식당)',
    onAir: '2021-11-21',
  },
  {
    dataNumber: 30,
    listing: true,
    state: '16',
    country: '245',
    sectors: '고기/구이',
    logo: '%EB%8D%A4+%EB%A1%9C%EA%B3%A0.png',
    name: '덤',
    address: '광주 남구 봉선2로 104',
    openTime: '11:30~22:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '062-673-4500',
    channelName: 1,
    thumbnail: '30.jpg',
    link: 'https://youtu.be/RZyiDOJadxU',
    title:
      '17년을 한 곳 에서 장사했는데 빚만 있고 고시원에 사는이유(유튜브판 골목식당)',
    onAir: '2021-11-28',
  },
  {
    dataNumber: 31,
    listing: true,
    state: '1',
    country: '30',
    sectors: '고기/구이',
    logo: '%EA%B3%B1%EC%B0%BD%EC%A0%95%EB%B9%84%EC%86%8C+%EB%A1%9C%EA%B3%A0.png',
    name: '곱창정비소',
    address: '서울 동대문구 한천로14길 61 1층',
    openTime: '11:00~03:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '02-2212-9055',
    channelName: 1,
    thumbnail: '31.jpg',
    link: 'https://youtu.be/FvmmfAizsyg',
    title:
      '친구3명이 동업으로 곱창집 차렸는데 뒤지기 일보직전 (유튜브판 골목식당)',
    onAir: '2021-12-12',
  },
  {
    dataNumber: 32,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '치즈스마일',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '32.jpg',
    link: 'https://youtu.be/ayRUiPrnHhE',
    title:
      '피자집 여사장님과 1박2일로 제주도 호텔에서 잔 이유(feat.브레이브걸스)',
    onAir: '2021-12-19',
  },
  {
    dataNumber: 33,
    listing: true,
    state: '2',
    country: '58',
    sectors: '찜/탕/찌개',
    logo: '%EB%AA%A8%EB%8F%84%EB%A6%AC%EA%B0%90%EC%9E%90%ED%83%95+%EB%A1%9C%EA%B3%A0.png',
    name: '모도리감자탕',
    address: '경기 시흥시 비둘기공원7길 39 2층',
    openTime: '11:00~22:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '0507-1461-3133',
    channelName: 1,
    thumbnail: '33.jpg',
    link: 'https://youtu.be/_YhFr3blIPU',
    title:
      '월세 10개월 밀리고 신용불량, 밤마다 소주2병씩 원샷때리는 이유 (유튜브판 골목식당)',
    onAir: '2021-12-26',
  },
  {
    dataNumber: 34,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '박광덕 천하장사 족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '34.jpg',
    link: 'https://youtu.be/UntbX303UNM',
    title: '박광덕 사장님이랑 술먹다가 싸대기 날라오길래 피했습니다',
    onAir: '2022-01-02',
  },
  {
    dataNumber: 35,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '모도리감자탕',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '35.jpg',
    link: 'https://youtu.be/1qgh-RzQBYI',
    title: '일매출 16000원 팔던 신용불량 모도리 사장님 ',
    onAir: '2022-01-09',
  },
  {
    dataNumber: 36,
    listing: true,
    state: '2',
    country: '72',
    sectors: '고기/구이',
    logo: '%EC%88%9C%EC%9D%B4%EB%84%A4+%EC%86%A1%ED%83%84%EB%B3%B8%EC%A0%90+%EB%A1%9C%EA%B3%A0.png',
    name: '순이네 송탄본점',
    address: '경기 평택시 지산2로 100',
    openTime: '09:00~24:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '031-666-0207',
    channelName: 1,
    thumbnail: '36.jpg',
    link: 'https://youtu.be/Werz7IXST9s',
    title: '모도리 도와주신 사장님네 찾아 가서 돈쭐냄 ',
    onAir: '2022-01-15',
  },
  {
    dataNumber: 37,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '삼삼공데이',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '37.jpg',
    link: 'https://youtu.be/58GvvIqEYx0',
    title:
      '강남 길바닥에서 전단지 뿌리던 여사장님 5개월 후 모습 (유튜브판 골목식당)',
    onAir: '2022-01-23',
  },
  {
    dataNumber: 38,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '덤',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '38.jpg',
    link: 'https://youtu.be/XkjSfRcMvo8',
    title: '미수금 6천만원, 월세15만원 고시원 사는 47살 벼랑끝 사장님 ',
    onAir: '2022-01-30',
  },
  {
    dataNumber: 39,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '곱창정비소',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '39.jpg',
    link: 'https://youtu.be/5JRNgjnjm_k',
    title: '식탁 위에 이불 깔고 쪽잠자면서 곱창파는 사장님 ',
    onAir: '2022-02-13',
  },
  {
    dataNumber: 40,
    listing: true,
    state: '15',
    country: '238',
    sectors: '고기/구이',
    logo: '%EC%9C%A1%EA%B0%92%EC%96%B4%EC%B9%98+%EB%A1%9C%EA%B3%A0.png',
    name: '육값어치',
    address: '전북 익산시 무왕로4길 36 1층 육값어치',
    openTime: '17:00~03:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '010-9201-9095',
    channelName: 1,
    thumbnail: '40.jpg',
    link: 'https://youtu.be/aWXG8fUYaoI',
    title: '학폭 피해자 10년후 모습 : 골목식당 역대급 빌런',
    onAir: '2022-02-19',
  },
  {
    dataNumber: 41,
    listing: true,
    state: '11',
    country: '180',
    sectors: '치킨/피자',
    logo: '%EC%B9%98%ED%82%A8%EC%97%90+%ED%99%80%EB%A6%B0+%EA%B9%8C%EB%8B%AD+%EB%A1%9C%EA%B3%A0.png',
    name: '치킨에 홀린 까닭',
    address:
      '부산 남구 용소로14번길 14 1층 홀까닭 , 치킨에홀린까닭 , HOLKKADAK',
    openTime: '15:00~01:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '0507-1498-3018',
    channelName: 1,
    thumbnail: '41.jpg',
    link: 'https://youtu.be/HRvesJTE0dA',
    title:
      '손님이없어 우울증에 원형탈모까지 온 부산 찐핵미모 여사장님 (은현장의 골목식당)',
    onAir: '2022-02-26',
  },
  {
    dataNumber: 42,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '만리삼구보쌈족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '42.jpg',
    link: 'https://youtu.be/hfDgUDFbNaA',
    title:
      '아버지 병원비 버느라 10년동안 하루도 못쉬고 일하는 만리삼구 사장님 ',
    onAir: '2022-03-05',
  },
  {
    dataNumber: 43,
    listing: true,
    state: '3',
    country: '78',
    sectors: '한식',
    logo: '%EC%B5%9C%EC%9D%B8%EC%8B%9D%ED%99%A9%ED%83%9C%EA%B3%A0%EC%9D%84+%EB%A1%9C%EA%B3%A0.png',
    name: '최인식황태고을',
    address: '인천 남동구 논고개로 61 라피에스타',
    openTime: '10:30~22:00',
    breakTime: '16:00~17:00',
    lastOrderTime: '21:30',
    closed: '없음',
    contact: '0507-1404-2088',
    channelName: 1,
    thumbnail: '43.jpg',
    link: 'https://youtu.be/kAyZU_xmDUA',
    title: '이혼하자는 아내 앞에서 무릎꿇고 매달리며 눈물흘리는 사장님 ',
    onAir: '2022-03-12',
  },
  {
    dataNumber: 44,
    listing: true,
    state: '2',
    country: '72',
    sectors: '족발/보쌈',
    logo: '%EC%82%BC%EB%8C%80%EB%B6%88%EC%A1%B1%EB%B0%9C+%EB%A1%9C%EA%B3%A0.png',
    name: '삼대불족발',
    address: '경기 평택시 안중읍 안현로서9길 20-4 1층 삼대불족발',
    openTime: '(월~금) 11:00~23:00\n(토~일) 10:00~23:00',
    breakTime: '',
    lastOrderTime: '22:30',
    closed: '없음',
    contact: '0507-1461-1280',
    channelName: 1,
    thumbnail: '44.jpg',
    link: 'https://youtu.be/jSp2j643ZjE',
    title:
      '27살 두아이 아빠, 원룸살면서 카드 돌려막기로 가게 월세내는 벼랑끝 사장님 ',
    onAir: '2022-03-19',
  },
  {
    dataNumber: 45,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '최인식황태고을',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '45.jpg',
    link: 'https://youtu.be/2i5JWqL3p60',
    title: '월세 3700만원 밀린 상태에서 보이스피싱 당하고 이혼 직전인 사장님 ',
    onAir: '2022-03-26',
  },
  {
    dataNumber: 46,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '삼대불족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '46.jpg',
    link: 'https://youtu.be/IztYsesfS-s',
    title: '족발배달 실수로 쌈장안보내놓고 쌈장값300원 환불해준다던 사장님 ',
    onAir: '2022-04-02',
  },
  {
    dataNumber: 47,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '치킨에 홀린 까닭',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '47.jpg',
    link: 'https://youtu.be/7GIRtKIHVXA',
    title: '부산 찐핵미모 여사장님이 홀서빙하니까 매출 20배 상승 ',
    onAir: '2022-04-09',
  },
  {
    dataNumber: 48,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '치즈스마일',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '48.jpg',
    link: 'https://youtu.be/pbdkVyn4-S4',
    title: '가게에서 먹고자며 한달 150벌던 피자집 여사장님 7개월 후 모습',
    onAir: '2022-04-16',
  },
  {
    dataNumber: 49,
    listing: true,
    state: '2',
    country: '74',
    sectors: '고기/구이',
    logo: '%EB%AF%B8%EC%82%AC%ED%99%94%EB%A1%9C+%EB%A1%9C%EA%B3%A0.png',
    name: '미사화로',
    address: '경기 하남시 미사강변북로30번길 63',
    openTime: '(월~금) 17:00~24:00\n(토~일) 13:00~24:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '0507-1348-3212',
    channelName: 1,
    thumbnail: '49.jpg',
    link: 'https://youtu.be/dUUEZX9hs0I',
    title: '천호동 200억 건물주의 삶- 장사의신 은현장',
    onAir: '2022-04-23',
  },
  {
    dataNumber: 50,
    listing: true,
    state: '2',
    country: '62',
    sectors: '고기/구이',
    logo: '%EC%98%A4%ED%92%88%EC%B1%84+%EB%A1%9C%EA%B3%A0.png',
    name: '오품채',
    address: '경기 양주시 고읍남로 6-16 광장프라자2층 203호',
    openTime: '11:20~22:00',
    breakTime: '15:30~16:30',
    lastOrderTime: '21:00',
    closed: '격주 월요일',
    contact: '0507-1498-5222',
    channelName: 1,
    thumbnail: '50.jpg',
    link: 'https://youtu.be/GAZzn_hygdo',
    title: '월세 낼 돈이 없어 노가다 뛰러가신 63세 사장님 (은현장의 골목식당)',
    onAir: '2022-04-30',
  },
  {
    dataNumber: 51,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '샐피',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '51.jpg',
    link: 'https://youtu.be/W8OsUXdvE5Y',
    title: '장사의신 출연했던 ',
    onAir: '2022-05-07',
  },
  {
    dataNumber: 52,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '오품채',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '52.jpg',
    link: 'https://youtu.be/tdGSe4lM3zE',
    title: '낼모레 칠순이신 사장님께 560만원 돈쭐냄 (은현장의 골목식당)',
    onAir: '2022-05-14',
  },
  {
    dataNumber: 53,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '벅벅버거',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '53.jpg',
    link: 'https://youtu.be/VFz4v2jPx4k',
    title:
      '이자30% 사채빚 1억2천지고 인생마감하려했던 23살 사장님(은현장의 골목식당)',
    onAir: '2022-05-21',
  },
  {
    dataNumber: 54,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '최인식황태고을',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '54.jpg',
    link: 'https://youtu.be/qXmDoiom7ag',
    title: '장사는 잘되지만 빚독촉에 시달리는 사장님(은현장의 골목식당)',
    onAir: '2022-05-28',
  },
  {
    dataNumber: 55,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '돼통령',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '55.jpg',
    link: 'https://youtu.be/MBV33Fjf72E',
    title: '장사의신 솔루션 후 1년만에 찾아간 돼통령 (은현장의 골목식당)',
    onAir: '2022-06-04',
  },
  {
    dataNumber: 56,
    listing: true,
    state: '11',
    country: '185',
    sectors: '고기/구이',
    logo: '%EC%B2%AD%EC%B6%98%EA%B0%88%EB%B9%84+%EB%A1%9C%EA%B3%A0.png',
    name: '청춘갈비',
    address: '부산 사상구 낙동대로1210번길 79 1층',
    openTime: '16:00~24:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '0507-1481-1114',
    channelName: 1,
    thumbnail: '56.jpg',
    link: 'https://youtu.be/tTo-WVI8tGI',
    title: '극단적인 선택을 3번이나 시도한 36살 (은현장의 골목식당)',
    onAir: '2022-06-11',
  },
  {
    dataNumber: 57,
    listing: true,
    state: '2',
    country: '59',
    sectors: '한식',
    logo: '%EC%98%A4%EB%8A%98%EC%A0%9C%EC%9C%A1%EC%96%B4%EB%95%8C%EC%9A%94+%EB%A1%9C%EA%B3%A0.png',
    name: '오늘제육어때요',
    address: '경기 안산시 단원구 선부광장남로 109 가동 2층',
    openTime: '11:00~01:00',
    breakTime: '없음',
    lastOrderTime: '0:50',
    closed: '없음',
    contact: '0507-1483-5026',
    channelName: 1,
    thumbnail: '57.jpg',
    link: 'https://youtu.be/_GKrKYOjin4',
    title: '일주일 후 폐업예정이라는 배달전문점 (은현장의 골목식당)',
    onAir: '2022-06-18',
  },
  {
    dataNumber: 58,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '청춘갈비',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '58.jpg',
    link: 'https://youtu.be/9TuAeLob3ek',
    title: '여친 만들러 부산 갑니다 (은현장의 골목식당)',
    onAir: '2022-06-25',
  },
  {
    dataNumber: 59,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '치킨에 홀린 까닭',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '58.jpg',
    link: 'https://youtu.be/9TuAeLob3ek',
    title: '여친 만들러 부산 갑니다 (은현장의 골목식당)',
    onAir: '2022-06-25',
  },
  {
    dataNumber: 60,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '미사화로',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '58.jpg',
    link: 'https://youtu.be/9TuAeLob3ek',
    title: '여친 만들러 부산 갑니다 (은현장의 골목식당)',
    onAir: '2022-06-25',
  },
  {
    dataNumber: 61,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '박광덕 천하장사 족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '59.jpg',
    link: 'https://youtu.be/iRuj-YbYwIU',
    title: '박광덕 형님 약올리다가 눈깔 찔렸네요',
    onAir: '2022-07-02',
  },
  {
    dataNumber: 62,
    listing: true,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: 'METHIN',
    address: 'https://methin.co.kr/',
    openTime: '온라인',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '070-8098-6538',
    channelName: 1,
    thumbnail: '60.jpg',
    link: 'https://youtu.be/e91qTpYpe7k',
    title: '워크맨 찍으러 갔다가 네고왕찍음 (은현장의 네고왕)',
    onAir: '2022-07-09',
  },
  {
    dataNumber: 63,
    listing: true,
    state: '1',
    country: '39',
    sectors: '카페/디저트',
    logo: '%EB%9D%BC%ED%8A%B8%EB%A6%AC+%EB%A1%9C%EA%B3%A0.png',
    name: '라트리',
    address: '서울 영등포구 영등포로3길 16 2층',
    openTime: '10:00~22:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '0507-1329-0668',
    channelName: 1,
    thumbnail: '61.jpg',
    link: 'https://youtu.be/O4XModtDzTk',
    title:
      '6살 딸아이와 가게에서 먹고자며 24시간 장사하는 여사장님 (은현장의 골목식당)',
    onAir: '2022-07-16',
  },
  {
    dataNumber: 64,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '라트리',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '62.jpg',
    link: 'https://youtu.be/5DjKHTPlRgs',
    title:
      '택배매출 하루만에 1억돌파,돈쭐맞고 로또까지맞은 라트리 (은현장의 골목식당)',
    onAir: '2022-07-23',
  },
  {
    dataNumber: 65,
    listing: true,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '소림마라면',
    address: 'https://m.smartstore.naver.com/gccompanyyy',
    openTime: '온라인',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '온라인',
    channelName: 1,
    thumbnail: '63.jpg',
    link: 'https://youtu.be/bn2WYO5OzOs',
    title: '네고왕 ',
    onAir: '2022-07-30',
  },
  {
    dataNumber: 66,
    listing: true,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '나는 장사의 신이다',
    address: 'https://naver.me/5AnOAHdO',
    openTime: '온라인',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '온라인',
    channelName: 1,
    thumbnail: '64.jpg',
    link: 'https://youtu.be/QnaHlNaNrqQ',
    title: '500억 자산가의 휴식 ',
    onAir: '2022-08-07',
  },
  {
    dataNumber: 67,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '오늘제육어때요',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '65.jpg',
    link: 'https://youtu.be/KMnVJsgGSSU',
    title: '라트리 영상 보고 저도 가게에서 숙식하면서 24시간 영업해보려고요 ',
    onAir: '2022-08-13',
  },
  {
    dataNumber: 68,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '삼대불족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '66.jpg',
    link: 'https://youtu.be/K0zsBWcjIdo',
    title: '박광덕의 ',
    onAir: '2022-08-21',
  },
  {
    dataNumber: 69,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '박광덕 천하장사 족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '66.jpg',
    link: 'https://youtu.be/K0zsBWcjIdo',
    title: '박광덕의 ',
    onAir: '2022-08-21',
  },
  {
    dataNumber: 70,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '벅벅버거',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '67.jpg',
    link: 'https://youtu.be/oM3BXFVNmo4',
    title: '불 타버린 벅벅, 화재현장 찾아가봤습니다 ',
    onAir: '2022-09-03',
  },
  {
    dataNumber: 71,
    listing: true,
    state: '15',
    country: '241',
    sectors: '고기/구이',
    logo: '%EA%B3%A8%EB%AA%A9+%EB%A1%9C%EA%B3%A0.png',
    name: '골목',
    address: '전북 전주시 완산구 신봉로 12 골목',
    openTime: '16:00~23:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '0507-1342-6446',
    channelName: 1,
    thumbnail: '68.jpg',
    link: 'https://youtu.be/uv3Vdz1x3JQ',
    title: '컨설팅하다 처음으로 포기하고 집갈뻔했습니다. ',
    onAir: '2022-09-11',
  },
  {
    dataNumber: 72,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '동해갈매기',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '69.jpg',
    link: 'https://youtu.be/zocTz_GYNW0',
    title: '손님이 많은데도 폐업위기에 놓인 사장님 ',
    onAir: '2022-09-18',
  },
  {
    dataNumber: 73,
    listing: true,
    state: '1',
    country: '32',
    sectors: '한식',
    logo: '%EB%AA%85%ED%98%84%EB%A7%8C%EA%B0%84%EC%9E%A5%EA%B2%8C%EC%9E%A5%EB%AC%B4%ED%95%9C%EB%A6%AC%ED%95%84+%ED%95%A9%EC%A0%95%EB%B3%B8%EC%A0%90+%EB%A1%9C%EA%B3%A0.png',
    name: '명현만간장게장무한리필 합정본점',
    address: '서울 마포구 양화로 45 메세나폴리스 123호~129호',
    openTime: '11:00~22:00',
    breakTime: '없음',
    lastOrderTime: '21:30',
    closed: '없음',
    contact: '0507-1302-3837',
    channelName: 1,
    thumbnail: '70.jpg',
    link: 'https://youtu.be/CP_s9HIv3U8',
    title: '명현만은 과대평가됐다',
    onAir: '2022-09-25',
  },
  {
    dataNumber: 74,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '골목',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '71.jpg',
    link: 'https://youtu.be/ygZB30N0V3g',
    title: '그냥 존나 이기적인 사장, 존나 미친 사장 ',
    onAir: '2022-10-09',
  },
  {
    dataNumber: 75,
    listing: true,
    state: '9',
    country: '148',
    sectors: '족발/보쌈',
    logo: '%EB%8C%80%ED%98%B8%EC%99%95%EC%A1%B1%EB%B0%9C+%EB%A1%9C%EA%B3%A0.png',
    name: '대호왕족발',
    address: '경남 창원시 진해구 경화시장로 62 1층 대호왕족발',
    openTime: '(월~금) 16:00~23:00\n(토~일,공휴일) 12:00~23:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '055-551-4161',
    channelName: 1,
    thumbnail: '72.jpg',
    link: 'https://youtu.be/Tkp587vY3vM',
    title: '갓난아기 업고 족발장사하는 벼랑끝 사장님 ',
    onAir: '2022-10-16',
  },
  {
    dataNumber: 76,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '육대포',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '73.jpg',
    link: 'https://youtu.be/fihmfHdH9Ik',
    title: '1년전 솔루션 해드렸지만 결국 폐업하는 사장님 ',
    onAir: '2022-10-23',
  },
  {
    dataNumber: 77,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '대호왕족발',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '74.jpg',
    link: 'https://youtu.be/pTA8E-XQ1WU',
    title: '후원금 3천만원은 둘째 수술비로 써야 될 것 같아요. ',
    onAir: '2022-11-06',
  },
  {
    dataNumber: 78,
    listing: false,
    state: null,
    country: null,
    sectors: null,
    logo: null,
    name: '봉득식당',
    address: null,
    openTime: null,
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '없음',
    contact: '없음',
    channelName: 1,
    thumbnail: '75.jpg',
    link: 'https://youtu.be/KyzqSW5BE0M',
    title:
      '솔루션하고 말 안 들어서 손절 쳤던 사장님, 현재는 손님으로 꽉 찼네요 ',
    onAir: '2022-11-13',
  },
  {
    dataNumber: 79,
    listing: true,
    state: '12',
    country: '199',
    sectors: '양식',
    logo: '%EB%85%BC%ED%94%BD%EC%8A%A4+%EB%A1%9C%EA%B3%A0.png',
    name: '논픽스',
    address: '대구 수성구 청수로9길 3 1층 논픽스',
    openTime: '11:30~22:00',
    breakTime: '없음',
    lastOrderTime: '없음',
    closed: '월요일',
    contact: '010-5102-7893',
    channelName: 1,
    thumbnail: '76.jpg',
    link: 'https://youtu.be/HcYAQtXt6ZY',
    title: '가게에서 1년째 텐트치고 먹고 자는 미슐랭출신 사장님 ',
    onAir: '2022-11-20',
  },
  {
    dataNumber: 80,
    listing: true,
    state: '6',
    country: '162',
    sectors: '양식',
    logo: '%EC%B9%98%ED%83%80%ED%95%98%EC%9A%B0%EC%8A%A4+%EB%A1%9C%EA%B3%A0.png',
    name: '치타하우스',
    address: '충북 청주시 서원구 내수동로108번길 18 2층, 3층',
    openTime: '17:00~04:00',
    breakTime: '없음',
    lastOrderTime: '3:30',
    closed: '없음',
    contact: '010-7139-7040',
    channelName: 1,
    thumbnail: '77.jpg',
    link: 'https://youtu.be/j4TD0RBj9cs',
    title: '29살에 빚3억, 인생 끝자락까지 내몰린 사장님들 ',
    onAir: '2022-11-27',
  },
]

router.get('/update', (req, res) => {
  list.map((item) => {
    const stores = new Store({
      dataNumber: item.dataNumber,
      listing: item.listing,
      state: item.state,
      country: item.country,
      sectors: item.sectors,
      logo: item.logo,
      name: item.name,
      address: item.address,
      openTime: item.openTime,
      breakTime: item.breakTime,
      lastOrderTime: item.lastOrderTime,
      closed: item.closed,
      contact: item.contact,
      channelName: item.channelName,
      thumbnail: item.thumbnail,
      link: item.link,
      title: item.title,
      onAir: item.onAir,
    }).save()
  })
  res.send('success')
})

module.exports = router
